apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: slack-notifications
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alertss'
        send_resolved: true
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: slack-notifications
      repeat_interval: 3h







kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitor
  creationTimestamp: "2021-09-15T16:00:59Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-14.6.1
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: monitor
  resourceVersion: "85043"

